---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar

  labels:
    app: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      terminationGracePeriodSeconds: 101
      containers:
        - name: sonar
          imagePullPolicy: Always
          image: registrydockerj.azurecr.io/sonarqube:21
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 4
            timeoutSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "90"]
          readinessProbe:
            httpGet:
              path: /health/status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              memory: 400Mi
              cpu: 500m

      dnsConfig:
        options:
          - name: single-request-reopen

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: pruebajenkinskubernetes
  name: sonar
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: sonar
  type: LoadBalancer
